typedef enum {
  GEAR_BUTTON_PRESSED_NONE,
  GEAR_BUTTON_PRESSED_GEAR_UP,
  GEAR_BUTTON_PRESSED_GEAR_DOWN,
  GEAR_BUTTON_PRESSED_FRONT_GEAR_UP,
  GEAR_BUTTON_PRESSED_FRONT_GEAR_DOWN,
  GEAR_BUTTON_PRESSED_RESET,
} gear_button_state_t;